server:
  port: 8080

spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/ticket_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect:
        hibernate: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        properties: 
          format-sql:Â true